### ISSUE TITLE
client versions listing

### ISSUE THREAD

**Issue by letsjustfixit** [getwarped/powershift#1]
Hey there!

I've just noticed the client version listing isn't complete yet:
**powershift client versions**
- v1.3.2
- v1.3.3
- v1.4.0
- v1.4.1
- v1.5.0
- v1.5.1
- v3.6.0-alpha.1

However alpha 2 has also been already released:
https://github.com/openshift/origin/releases/tag/v3.6.0-alpha.2
Could you please point me to the place where the possible client versions are fetched from to make it possible to install alpha 2?

Thanks & Regards,
Fixer

**Comment by GrahamDumpleton** [comment]
They are fetched based on filenames listed on:

* https://github.com/openshift/origin/releases

The package has already been updated though.

If used ``pipsi`` to install it, to upgrade run:

```
pipsi upgrade powershift-cli[all]
```

of if you used ``pip``, use:

```
pip install -U "powershift-cli>1.1.16"
```

You can then do:

```
powershift client install v3.6.0-alpha.2
```

**Comment by GrahamDumpleton** [comment]
Just be aware that looks like they may have changed something in ``oc cluster up`` as it relates to MacOS X as it now longer works there and I may have to tweak how ``powershift cluster`` works. I don't know if this affects Windows as well.

**Comment by GrahamDumpleton** [comment]
May actually be working. Issue may have been caused by slow pull down of haproxy router image in background. The alpha 2 image is much larger than alpha 1, now 1.0GB in size, rather than 650MB as before. I only have slow Internet.

**Comment by letsjustfixit** [comment]
Thank you very much, that was a really-really fast resolve ! 🥇

**Comment by GrahamDumpleton** [comment]
I had had it on my TODO list for a few days before you raised it and it is a quick change. :-)
